# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'TODO: add repo description.'
repo_name: sale-workflow
repo_slug: sale-workflow
repo_website: https://github.com/OCA/sale-workflow
travis_apt_packages: []
travis_apt_sources: []

