from . import price_compliance_threshold_config_mixin
from . import price_compliance_threshold_tier_mixin
from . import res_company
from . import res_config_settings
from . import product_category
from . import product_product
from . import product_template
from . import sale_order_line
from . import sale_order
