{
    "name": "Sale Order Customer No Autofollow",
    "summary": "Do not add customer as follower in Sales Orders",
    "author": "Cetmix,Odoo Community Association (OCA)",
    "version": "15.0.1.0.0",
    "website": "https://github.com/OCA/sale-workflow",
    "category": "Sale",
    "depends": ["sale"],
    "maintainers": ["dessanhemrayev", "CetmixGitDrone"],
    "data": ["views/res_config_settings.xml"],
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False,
}
