-
  Sale config
-
  !python {model: sale.config.settings}: |
    config_obj = self.env.get('sale.config.settings')
    if config_obj:
        vals = {
            'group_multi_salesteams': 'True',
            'group_sale_delivery_address': 'True',
        }
        config_id = config_obj.create(vals)
        config = config_obj.browse(config_id)
        config.execute()
        