[project]
name = "odoo-addons-oca-sale-workflow"
version = "19.0.20260122.1"
dependencies = [
    "odoo-addon-sale_advance_payment==19.0.*",
    "odoo-addon-sale_automatic_workflow==19.0.*",
    "odoo-addon-sale_cancel_restrict==19.0.*",
    "odoo-addon-sale_commercial_partner==19.0.*",
    "odoo-addon-sale_exception==19.0.*",
    "odoo-addon-sale_fixed_discount==19.0.*",
    "odoo-addon-sale_force_invoiced==19.0.*",
    "odoo-addon-sale_order_disable_user_autosubscribe==19.0.*",
    "odoo-addon-sale_order_general_discount==19.0.*",
    "odoo-addon-sale_order_line_date==19.0.*",
    "odoo-addon-sale_order_line_note==19.0.*",
    "odoo-addon-sale_order_line_price_history==19.0.*",
    "odoo-addon-sale_order_line_tag==19.0.*",
    "odoo-addon-sale_order_priority==19.0.*",
    "odoo-addon-sale_order_type==19.0.*",
    "odoo-addon-sale_partner_incoterm==19.0.*",
    "odoo-addon-sale_require_po_doc==19.0.*",
    "odoo-addon-sale_stock_picking_note==19.0.*",
    "odoo-addon-sale_stock_reference_by_line==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
